### ISSUE TITLE
What's the art portal all about?

### ISSUE THREAD

**Issue by konstin** [MTres19/stk-docs#24]
I saw art portal navigation bars at the bottom of multiple pages. There also a [page](https://supertuxkart.net/Art_Portal) that an excerpt from the Get Involved page.

So what is the art portal all about?

**Comment by MTres19** [comment]
The art portal is just links to art-related pages. It's transcluded into
the get involved page. The navigation bar is just to make things easier to
get back to the index pages from the middle of a tutorial.

**Comment by MTres19** [comment]
The navigation bar is the ArtPortalNav template.

**Comment by konstin** [comment]
Solved on irc.
