### ISSUE TITLE
Fill out communication page

### ISSUE THREAD

**Issue by MTres19** [MTres19/stk-docs#3]
Some ideas for rules:

* Always post source (.blend, .kra)
* Answer questions completely
* Search for your question first before asking again
...

Any other ideas? It seems like an important page to have (though not critical), but I'm having trouble thinking of ideas for this one, since I've never administered a forum or anything like that.

**Comment by MTres19** [comment]
* Don't waste developers' time with trivial requests.
* Respect that developers can't always respond right away.
* Be somewhat humble: don't, for example, constantly ask for your track to be included in main.

**Comment by konstin** [comment]
I don't think there's any use in writing more about how to be polite in the wiki. People who disobey the rules you stated above won't read a code of conduct in a wiki anyway. Though there's for sure a guide on internet etiquette somewhere that matches STK's need and which we can refer to if needed.

**Comment by MTres19** [comment]
I did some more work on the page. I'm not sure it's complete, but I feel that it's complete enough to close this issue. I actually couldn't find a great internet etiquette guide that really seemed relevant, but I actually think that if people read the page, perhaps it might make them think just a bit. And even that might be enough.
